---
dataset_name: MNIST
model_name: LeNet5
distributed_algorithm: GTG_shapley_value
optimizer_name: SGD
worker_number: 30
batch_size: 64
round: 1
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 2
learning_rate: 0.01
...
